spring.application.name=sabback-end
spring.datasource.url=jdbc:mysql://localhost:3306/black_sabbath_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=matheus2006$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
